### ISSUE TITLE
SBT fails with: java.lang.NoClassDefFoundError: com/android/tools/lint/detector/api/Issue

### ISSUE THREAD

**Issue by soc** [Taig/Hello-Scala#28]
I started with a fresh install, downloaded the SDK, installed Android stuff, set `ANDROID_HOME`, ran sbt:

```
sbt                       
[info] Loading global plugins from /home/soc/.sbt/0.13/plugins
[info] Loading project definition from /home/soc/Entwicklung/Hello-Scala/project
Repositories:
  ivy:file:/home/soc/.sbt/0.13/plugins/target/resolution-cache/[organization]/[module](/scala_[scalaVersion])(/sbt_[sbtVersion])/[revision]/resolved.xml.[ext]
  inter-project
  ivy:https://repo.typesafe.com/typesafe/ivy-releases/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
  ivy:https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
  ivy:file://${ivy.home}/local/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
  https://repo1.maven.org/maven2/
Resolving default:hello-scala-build:0.1-SNAPSHOT
  io.taig.sbt:scalariform;sbtVersion=0.13;scalaVersion=2.10:1.6.0:compile->default(compile)
  org.scala-android:sbt-android;sbtVersion=0.13;scalaVersion=2.10:1.6.0:compile->default(compile)
  org.scala-lang:scala-compiler:2.10.6:ensime-internal->default(compile)
  org.scala-lang:scala-compiler:2.10.6:scala-tool->default
  org.scala-lang:scala-compiler:2.10.6:scala-tool->optional(default)
  org.scala-lang:scala-library:2.10.6:ensime-internal->default(compile)
  org.scala-lang:scala-library:2.10.6:provided->default(compile)
  org.scala-lang:scala-library:2.10.6:scala-tool->default
  org.scala-lang:scala-library:2.10.6:scala-tool->optional(default)
  org.scala-lang:scala-reflect:2.10.6:ensime-internal->default(compile)
  org.scala-lang:scalap:2.10.6:ensime-internal->default(compile)
  org.scala-sbt:global-plugins;sbtVersion=0.13;scalaVersion=2.10:0.0:compile->default(compile)
  org.scala-sbt:sbt:0.13.11:provided->default(compile)
Resolution done
  args4j:args4j:2.0.12:compile->compile
  com.android.databinding:compilerCommon:2.0.0:compile->compile
    exclude(net.sf.proguard, *)
  com.android.tools:common:25.0.0:compile->compile
    exclude(org.bouncycastle, *)
  com.android.tools:sdk-common:25.0.0:compile->compile
    exclude(org.bouncycastle, *)
  com.android.tools:sdklib:25.0.0:compile->compile
    exclude(org.bouncycastle, *)
  com.android.tools.build:builder:2.0.0:compile->default
    exclude(org.bouncycastle, *)
  com.android.tools.build:builder:2.0.0:compile->compile
    exclude(net.sf.proguard, *)
  com.android.tools.build:builder-model:2.0.0:compile->compile
    exclude(org.bouncycastle, *)
  com.android.tools.build:builder-test-api:2.0.0:compile->compile
    exclude(org.bouncycastle, *)
  com.android.tools.build:gradle-api:2.0.0:compile->compile
    exclude(net.sf.proguard, *)
  com.android.tools.build:gradle-core:2.0.0:compile->default
    exclude(net.sf.proguard, *)
  com.android.tools.build:manifest-merger:25.0.0:compile->compile
    exclude(org.bouncycastle, *)
  com.android.tools.build:transform-api:2.0.0-deprecated-use-gradle-api:compile->compile
    exclude(net.sf.proguard, *)
  com.android.tools.ddms:ddmlib:25.0.0:compile->compile
    exclude(org.bouncycastle, *)
  com.android.tools.jack:jack-api:0.9.0:compile->compile
    exclude(org.bouncycastle, *)
  com.android.tools.jill:jill-api:0.9.0:compile->compile
    exclude(org.bouncycastle, *)
  com.android.tools.lint:lint:25.0.0:compile->default
  com.android.tools.lint:lint-checks:25.0.0:compile->compile
  com.eed3si9n:sbt-assembly;sbtVersion=0.13;scalaVersion=2.10:0.14.1:compile->compile
  com.github.alexarchambault:coursier-cache_2.10:1.0.0-M9:compile->compile
  com.github.alexarchambault:coursier-sbt-plugin;sbtVersion=0.13;scalaVersion=2.10:1.0.0-M9:compile->default
  com.github.alexarchambault:coursier_2.10:1.0.0-M9:compile->compile
  com.github.julien-truffaut:monocle-core_2.10:1.1.0:compile->compile
  com.github.julien-truffaut:monocle-macro_2.10:1.1.0:compile->compile
  com.github.mpeltonen:sbt-idea;sbtVersion=0.13;scalaVersion=2.10:1.6.0:compile->default
  com.googlecode.javaewah:JavaEWAH:0.7.9:compile->compile
  com.hanhuy.sbt:bintray-update-checker_2.10:0.1:compile->default
  com.jcraft:jsch:0.1.50:provided->default
  com.jcraft:jsch:0.1.50:compile->compile
  com.lihaoyi:ammonite-terminal_2.10:0.5.0:compile->compile
  com.scalapenos:sbt-prompt;sbtVersion=0.13;scalaVersion=2.10:0.2.1:compile->compile
  com.squareup:javawriter:2.5.0:compile->compile
    exclude(org.bouncycastle, *)
  com.thoughtworks.paranamer:paranamer:2.6:provided->compile
    exclude(org.scala-lang, scalap)
  com.typesafe.sbt:sbt-git;sbtVersion=0.13;scalaVersion=2.10:0.6.4:compile->compile
  com.typesafe.sbt:sbt-native-packager;sbtVersion=0.13;scalaVersion=2.10:1.1.0-RC1:compile->compile
  com.typesafe.sbt:sbt-proguard;sbtVersion=0.13;scalaVersion=2.10:0.2.2:compile->compile
  com.typesafe.sbteclipse:sbteclipse-plugin;sbtVersion=0.13;scalaVersion=2.10:4.0.0:compile->compile
  commons-codec:commons-codec:1.4:compile->compile
  commons-io:commons-io:2.0.1:compile->compile
  commons-logging:commons-logging:1.1.1:compile->compile
  io.argonaut:argonaut_2.10:6.1:compile->compile
  io.taig.sbt:scalariform;sbtVersion=0.13;scalaVersion=2.10:1.6.0:compile->default
  javax.annotation:jsr250-api:1.0:compile->compile
    exclude(javax.el, el-api)
    exclude(org.jboss.ejb3, jboss-ejb3-api)
    exclude(org.jboss.interceptor, jboss-interceptor-api)
  javax.enterprise:cdi-api:1.0:compile->compile
    exclude(javax.el, el-api)
    exclude(org.jboss.ejb3, jboss-ejb3-api)
    exclude(org.jboss.interceptor, jboss-interceptor-api)
  javax.inject:javax.inject:1:compile->compile
    exclude(javax.el, el-api)
    exclude(org.jboss.ejb3, jboss-ejb3-api)
    exclude(org.jboss.interceptor, jboss-interceptor-api)
  jline:jline:2.13:provided->default
  net.orfjackal.retrolambda:retrolambda:2.1.0:compile->default
  org.antlr:ST4:4.0.8:compile->compile
    exclude(net.sf.proguard, *)
  org.antlr:antlr:3.5.2:compile->compile
    exclude(net.sf.proguard, *)
  org.antlr:antlr-runtime:3.5.2:compile->compile
    exclude(net.sf.proguard, *)
  org.apache.ant:ant:1.9.6:compile->default
  org.apache.ant:ant-launcher:1.9.6:compile->compile
  org.apache.commons:commons-compress:1.6:compile->default
  org.apache.httpcomponents:httpclient:4.1.3:compile->compile
  org.apache.httpcomponents:httpcore:4.1.4:compile->compile
  org.apache.maven:maven-artifact:3.3.3:compile->compile
    exclude(org.apache.maven.wagon, wagon-provider-api)
  org.apache.maven:maven-model:3.3.3:compile->compile
  org.apache.maven:maven-plugin-api:3.3.3:compile->compile
  org.bouncycastle:bcpkix-jdk15on:1.51:compile->default
  org.bouncycastle:bcprov-jdk15on:1.51:compile->compile
  org.codehaus.plexus:plexus-classworlds:2.5.2:compile->compile
  org.codehaus.plexus:plexus-component-annotations:1.5.5:compile->compile
  org.codehaus.plexus:plexus-utils:3.0.20:compile->compile
  org.eclipse.jdt.core.compiler:ecj:4.4.2:compile->compile
  org.eclipse.jgit:org.eclipse.jgit:3.3.2.201404171909-r:compile->compile
  org.eclipse.jgit:org.eclipse.jgit.archive:3.3.2.201404171909-r:compile->compile
  org.eclipse.jgit:org.eclipse.jgit.pgm:3.3.2.201404171909-r:compile->default
  org.eclipse.jgit:org.eclipse.jgit.ui:3.3.2.201404171909-r:compile->compile
  org.eclipse.sisu:org.eclipse.sisu.inject:0.3.0:compile->compile
  org.eclipse.sisu:org.eclipse.sisu.plexus:0.3.0:compile->compile
  org.ensime:ensime-sbt;sbtVersion=0.13;scalaVersion=2.10:0.4.0:compile->default
  org.fusesource.jansi:jansi:1.11:provided->compile
  org.jacoco:org.jacoco.core:0.7.4.201502262128:compile->compile
    exclude(net.sf.proguard, *)
  org.javassist:javassist:3.20.0-GA:compile->default
  org.json4s:json4s-ast_2.10:3.2.10:provided->compile
    exclude(org.scala-lang, scalap)
  org.json4s:json4s-core_2.10:3.2.10:provided->compile
    exclude(org.scala-lang, scalap)
  org.osgi:org.osgi.core:4.3.1:compile->compile
  org.ow2.asm:asm:5.0.4:compile->compile
  org.ow2.asm:asm-all:5.0.4:compile->default
  org.ow2.asm:asm-commons:5.0.4:compile->compile
  org.ow2.asm:asm-debug-all:5.0.1:compile->compile
    exclude(net.sf.proguard, *)
  org.ow2.asm:asm-tree:5.0.4:compile->compile
  org.pantsbuild:jarjar:1.6.0:compile->default
  org.scala-android:sbt-android;sbtVersion=0.13;scalaVersion=2.10:1.6.0:compile->compile
  org.scala-lang:scala-compiler:2.10.6:provided->default,scala-tool->default,compile->compile
  org.scala-lang:scala-compiler:2.10.6:ensime-internal->default
  org.scala-lang:scala-library:2.10.6:provided->default,scala-tool->default,compile->compile
  org.scala-lang:scala-library:2.10.6:ensime-internal->default
  org.scala-lang:scala-reflect:2.10.6:ensime-internal->default
  org.scala-lang:scala-reflect:2.10.6:provided->default,scala-tool->compile,compile->compile
  org.scala-lang:scalap:2.10.6:compile->compile
  org.scala-lang:scalap:2.10.6:ensime-internal->default
  org.scala-lang.modules:scala-pickling_2.10:0.10.1:provided->compile
  org.scala-sbt:actions:0.13.11:provided->compile
  org.scala-sbt:api:0.13.11:provided->compile
  org.scala-sbt:apply-macro:0.13.11:provided->compile
  org.scala-sbt:cache:0.13.11:provided->compile
  org.scala-sbt:classfile:0.13.11:provided->compile
  org.scala-sbt:classpath:0.13.11:provided->compile
  org.scala-sbt:collections:0.13.11:provided->compile
  org.scala-sbt:command:0.13.11:provided->compile
  org.scala-sbt:compile:0.13.11:provided->compile
  org.scala-sbt:compiler-integration:0.13.11:provided->compile
  org.scala-sbt:compiler-interface:0.13.11:provided->compile
  org.scala-sbt:compiler-ivy-integration:0.13.11:provided->compile
  org.scala-sbt:completion:0.13.11:provided->compile
  org.scala-sbt:control:0.13.11:provided->compile
  org.scala-sbt:cross:0.13.11:provided->compile
  org.scala-sbt:global-plugins;sbtVersion=0.13;scalaVersion=2.10:0.0:compile->compile
  org.scala-sbt:global-plugins;sbtVersion=0.13;scalaVersion=2.10:0.0:compile->compile
  org.scala-sbt:global-plugins;sbtVersion=0.13;scalaVersion=2.10:0.0:compile->compile
  org.scala-sbt:global-plugins;sbtVersion=0.13;scalaVersion=2.10:0.0:compile->compile
  org.scala-sbt:incremental-compiler:0.13.11:provided->compile
  org.scala-sbt:interface;component=xsbti:0.13.11:provided->compile
  org.scala-sbt:io:0.13.11:provided->compile
  org.scala-sbt:ivy:0.13.11:provided->compile
  org.scala-sbt:launcher-interface:1.0.0-M1:provided->default
  org.scala-sbt:logging:0.13.11:provided->compile
  org.scala-sbt:logic:0.13.11:provided->compile
  org.scala-sbt:main:0.13.11:provided->compile
  org.scala-sbt:main-settings:0.13.11:provided->compile
  org.scala-sbt:persist:0.13.11:provided->compile
  org.scala-sbt:process:0.13.11:provided->compile
  org.scala-sbt:relation:0.13.11:provided->compile
  org.scala-sbt:run:0.13.11:provided->compile
  org.scala-sbt:sbt:0.13.11:provided->compile
  org.scala-sbt:serialization_2.10:0.1.2:provided->default
  org.scala-sbt:task-system:0.13.11:provided->compile
  org.scala-sbt:tasks:0.13.11:provided->compile
  org.scala-sbt:test-agent:0.13.11:provided->compile
  org.scala-sbt:test-interface:1.0:provided->default
  org.scala-sbt:testing:0.13.11:provided->compile
  org.scala-sbt:tracking:0.13.11:provided->compile
  org.scala-sbt.ivy:ivy:2.3.0-sbt-2cc8d2761242b072cedb0a04cb39435c4fa24f9a:provided->default
  org.scala-tools.sbinary:sbinary_2.10:0.4.2:provided->compile
  org.scalactic:scalactic_2.10:2.2.1:compile->default
  org.scalamacros:quasiquotes_2.10:2.0.1:provided->compile,compile->compile
  org.scalariform:sbt-scalariform;sbtVersion=0.13;scalaVersion=2.10:1.6.0:compile->compile
  org.scalariform:scalariform_2.10:0.1.8:compile->compile
  org.scalaz:scalaz-concurrent_2.10:7.1.2:compile->compile
  org.scalaz:scalaz-core_2.10:7.1.2:compile->default
  org.scalaz:scalaz-effect_2.10:7.1.2:compile->default
  org.spire-math:jawn-parser_2.10:0.6.0:provided->compile
    exclude(org.scala-lang, scalap)
  org.spire-math:json4s-support_2.10:0.6.0:provided->compile
    exclude(org.scala-lang, scalap)
  org.tukaani:xz:1.4:compile->compile
Fetching artifacts
Fetching artifacts: done
java.lang.NoClassDefFoundError: com/android/tools/lint/detector/api/Issue
    at android.Keys$.<init>(keys.scala:262)
    at android.Keys$.<clinit>(keys.scala)
    at android.AndroidPlugin$.<init>(autoPlugin.scala:12)
    at android.AndroidPlugin$.<clinit>(autoPlugin.scala)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at sbt.ModuleUtilities$.getObject(ModuleUtilities.scala:14)
    at sbt.ModuleUtilities$.getCheckedObject(ModuleUtilities.scala:20)
    at sbt.ModuleUtilities$$anonfun$getCheckedObjects$1.apply(ModuleUtilities.scala:23)
    at sbt.ModuleUtilities$$anonfun$getCheckedObjects$1.apply(ModuleUtilities.scala:23)
    at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:376)
    at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:376)
    at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1085)
    at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1077)
    at scala.collection.immutable.Stream.foreach(Stream.scala:548)
    at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)
    at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:176)
    at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:45)
    at scala.collection.TraversableLike$class.to(TraversableLike.scala:629)
    at scala.collection.AbstractTraversable.to(Traversable.scala:105)
    at scala.collection.TraversableOnce$class.toList(TraversableOnce.scala:257)
    at scala.collection.AbstractTraversable.toList(Traversable.scala:105)
    at scala.collection.immutable.List.$plus$plus(List.scala:193)
    at sbt.PluginDiscovery$.discoverAll(PluginDiscovery.scala:38)
    at sbt.Load$.loadPlugins(Load.scala:850)
    at sbt.Load$.loadPluginDefinition(Load.scala:807)
    at sbt.Load$.buildPlugins(Load.scala:802)
    at sbt.Load$.plugins(Load.scala:790)
    at sbt.Load$.loadUnit(Load.scala:441)
    at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:291)
    at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:291)
    at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:91)
    at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:90)
    at sbt.BuildLoader.apply(BuildLoader.scala:140)
    at sbt.Load$.loadAll(Load.scala:344)
    at sbt.Load$.loadURI(Load.scala:299)
    at sbt.Load$.load(Load.scala:295)
    at sbt.Load$.load(Load.scala:286)
    at sbt.Load$.apply(Load.scala:140)
    at sbt.Load$.defaultLoad(Load.scala:36)
    at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:492)
    at sbt.BuiltinCommands$.doLoadProject(Main.scala:492)
    at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:484)
    at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:484)
    at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
    at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
    at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
    at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
    at sbt.Command$.process(Command.scala:93)
    at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
    at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
    at sbt.State$$anon$1.process(State.scala:184)
    at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
    at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.MainLoop$.next(MainLoop.scala:96)
    at sbt.MainLoop$.run(MainLoop.scala:89)
    at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
    at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
    at sbt.Using.apply(Using.scala:24)
    at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
    at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
    at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
    at sbt.MainLoop$.runLogged(MainLoop.scala:22)
    at sbt.StandardMain$.runManaged(Main.scala:54)
    at sbt.xMain.run(Main.scala:29)
    at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
    at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
    at xsbt.boot.Launch$.run(Launch.scala:109)
    at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
    at xsbt.boot.Launch$.launch(Launch.scala:117)
    at xsbt.boot.Launch$.apply(Launch.scala:18)
    at xsbt.boot.Boot$.runImpl(Boot.scala:41)
    at xsbt.boot.Boot$.main(Boot.scala:17)
    at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.lang.ClassNotFoundException: com.android.tools.lint.detector.api.Issue
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at android.Keys$.<init>(keys.scala:262)
    at android.Keys$.<clinit>(keys.scala)
    at android.AndroidPlugin$.<init>(autoPlugin.scala:12)
    at android.AndroidPlugin$.<clinit>(autoPlugin.scala)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at sbt.ModuleUtilities$.getObject(ModuleUtilities.scala:14)
    at sbt.ModuleUtilities$.getCheckedObject(ModuleUtilities.scala:20)
    at sbt.ModuleUtilities$$anonfun$getCheckedObjects$1.apply(ModuleUtilities.scala:23)
    at sbt.ModuleUtilities$$anonfun$getCheckedObjects$1.apply(ModuleUtilities.scala:23)
    at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:376)
    at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:376)
    at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1085)
    at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1077)
    at scala.collection.immutable.Stream.foreach(Stream.scala:548)
    at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)
    at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:176)
    at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:45)
    at scala.collection.TraversableLike$class.to(TraversableLike.scala:629)
    at scala.collection.AbstractTraversable.to(Traversable.scala:105)
    at scala.collection.TraversableOnce$class.toList(TraversableOnce.scala:257)
    at scala.collection.AbstractTraversable.toList(Traversable.scala:105)
    at scala.collection.immutable.List.$plus$plus(List.scala:193)
    at sbt.PluginDiscovery$.discoverAll(PluginDiscovery.scala:38)
    at sbt.Load$.loadPlugins(Load.scala:850)
    at sbt.Load$.loadPluginDefinition(Load.scala:807)
    at sbt.Load$.buildPlugins(Load.scala:802)
    at sbt.Load$.plugins(Load.scala:790)
    at sbt.Load$.loadUnit(Load.scala:441)
    at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:291)
    at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:291)
    at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:91)
    at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:90)
    at sbt.BuildLoader.apply(BuildLoader.scala:140)
    at sbt.Load$.loadAll(Load.scala:344)
    at sbt.Load$.loadURI(Load.scala:299)
    at sbt.Load$.load(Load.scala:295)
    at sbt.Load$.load(Load.scala:286)
    at sbt.Load$.apply(Load.scala:140)
    at sbt.Load$.defaultLoad(Load.scala:36)
    at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:492)
    at sbt.BuiltinCommands$.doLoadProject(Main.scala:492)
    at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:484)
    at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:484)
    at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
    at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
    at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
    at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
    at sbt.Command$.process(Command.scala:93)
    at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
    at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
    at sbt.State$$anon$1.process(State.scala:184)
    at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
    at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.MainLoop$.next(MainLoop.scala:96)
    at sbt.MainLoop$.run(MainLoop.scala:89)
    at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
    at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
    at sbt.Using.apply(Using.scala:24)
    at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
    at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
    at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
    at sbt.MainLoop$.runLogged(MainLoop.scala:22)
    at sbt.StandardMain$.runManaged(Main.scala:54)
    at sbt.xMain.run(Main.scala:29)
    at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
    at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
    at xsbt.boot.Launch$.run(Launch.scala:109)
    at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
    at xsbt.boot.Launch$.launch(Launch.scala:117)
    at xsbt.boot.Launch$.apply(Launch.scala:18)
    at xsbt.boot.Boot$.runImpl(Boot.scala:41)
    at xsbt.boot.Boot$.main(Boot.scala:17)
    at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.NoClassDefFoundError: com/android/tools/lint/detector/api/Issue
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
```

Any ideas what could be the cause?

**Comment by taig** [comment]
@soc This has been resolved on your end if I remember it correctly from Gitter?
